# Bugs SMP Plugin Config

# Enable or Disable Features
commands:
  # Set gamemode survival command
  gms: true
  # Set gamemode adventure command
  gma: true
  # Set gamemode creative command
  gmc: true
  # Set gamemode spectator command
  gmt: true
  # Player info command
  player-info: true
  # Ping command
  ping: true
  # invsee, endersee, and armorsee command
  invsee: false
  # Ban stick
  banstick: true
  # Kick Stick
  kickstick: true

# Enable or Disable storing certain information
log-data:
  # Log IP
  log-address: true
  # Log logout location
  log-logout-location: true

# Enable or Disable log files
logging:
  # Enable simple log file
  simple-log: true