name: BugsSmpPlugin
version: '${project.version}'
main: me.bbugsco.bugssmpplugin.BugsSmpPlugin
api-version: 1.19
authors: [ BbugsCO ]
description: plugin for Bugs SMP

commands:
  bugssmpreload:
    description: Reloads config for BugsSmpPlugin
    usage: /bugssmpreload
    permission: bugs-smp.reload
  gma:
    description: Set gamemode adventure
    usage: /gma
    permission: bugs-smp.gma
  gms:
    description: Set gamemode survival
    usage: /gms
    permission: bugs-smp.gms
  gmt:
    description: Set gamemode spectator
    usage: /gmt
    permission: bugs-smp.gmt
  gmc:
    description: Set gamemode creative
    usage: /gmc
    permission: bugs-smp.gmc
  playerinfo:
    description: Gives certain information about a player
    usage: /playerinfo <player>
    permission: bugs-smp.playerinfo
  ping:
    description: Gives ping of given player
    usage: /ping <player>
    permission: bugs-smp.ping
  banstick:
    description: command to get the ban stick
    usage: /banstick
    permission: bugs-smp.banstick
  kickstick:
    description: command to get the kick stick
    usage: /kickstick
    permission: bugs-smp.kickstick

permissions:
  bugs-smp.reload:
    description: Permission to run /bugssmpreload
    default: op
  bugs-smp.gma:
    description: Permission to run /gma
    default: op
  bugs-smp.gms:
    description: Permission to run /gms
    default: op
  bugs-smp.gmt:
    description: Permission to run /gmt
    default: op
  bugs-smp.gmc:
    description: Permission to run /gmc
    default: op
  bugs-smp.playerinfo:
    description: Permission to run /playerinfo
    default: op
  bugs-smp.ping:
    description: Permission to run /ping
    default: op
  bugs-smp.banstick:
    description: Permission to run /banstick
    default: op
  bugs-smp.banstick.bypass:
    description: Can't be affected by ban stick
    default: false
  bugs-smp.banstick.use:
      description: Permission to use ban stick
      default: op
  bugs-smp.kickstick:
    description: Permission to run /kickstick
    default: op
  bugs-smp.kickstick.bypass:
      description: Can't be affected by kick stick
      default: false
  bugs-smp.kickstick.use:
    description: Permission to use kick stick
    default: op